on:
  push:
    branches: "*.0-*"
  pull_request:
    branches: "*.0"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'adhoc-dev' }}
    steps:
      - name: Clone adhoc-dev
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
        uses: actions/checkout@v3
      - name: Push to ingadhoc
        run: git push --force https://github.com/ingadhoc/${GITHUB_REPOSITORY#'adhoc-dev/'}.git HEAD
      - name: PR link
        run: echo 'Create pr by visiting https://github.com/ingadhoc/'${GITHUB_REPOSITORY#'adhoc-dev/'}'/pull/new/'${GITHUB_REF_NAME}
